config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true,  length: {minimum: 3, maximum: 50}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments , dependent: :destroy
  has_one_attached :image

  validates :title, presence: true, uniqueness: true, length: {minimum: 3, maximum: 80}
  validates :body, presence: true, uniqueness: true, length: {minimum: 10, maximum: 800}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include ExceptionHandler

  before_action :authenticate_user!
  protect_from_forgery

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:new, :create, :destroy]
  before_action :set_comment, only: [:destroy]

  def index
    @comments = Comment.all
  end

  def new
    @comment = @post.comments.new(@post)
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to post_path(@post)
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post), :notice => "comment successfully destroy!"
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
    authorize @comment
  end
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
    extend ActiveSupport::Concern

  included do
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    private

    def user_not_authorized
      flash[:alert] = 'You are not authorized to perform this action.'
      redirect_to(request.referer || root_path)
    end

    def record_not_found
      flash[:alert] = 'Record Not Found.'
      redirect_to(request.referer || root_path)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.new
  end

  def show
  end

  def create
    @post = current_user.posts.build(post_params)
     if @post.save
      flash[:notice] = "Post Successfully Created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    authorize @post
    if @post.update(post_params)
      flash[:notice] = 'Post updated!'
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    authorize @post
    @post.destroy
    redirect_to posts_path, :notice => "Post successfully destroy!"
  end

private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_index.html.erb
<section id="app">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <div class="comment">
          <% @post.comments.each do |comment| %>
            <div class="single-comment mb-2">
              <div class="mb-2"><%= comment.content%></div>
              <% if user_signed_in? %>
                <% if comment.user == current_user %>
                    <%= link_to "Delete", post_comment_path(comment.post, comment) , method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn-custom-delete primaryContained' %>
                <% end %>
              <% end %>
            </div><br>
          <% end %>
        </div><!--End Comment-->
      </div><!--End col -->
    </div><!-- End row -->
  </div><!--End Container -->
</section>

app/views/comments/_new.html.erb
<section id="app">
  <div class="container">
    <div class="row align-comment">
      <div class="col-6">
        <%= simple_form_for([ @post , @post.comments.build]) do |f| %>
        <p><%= f.text_area :content, label: false, placeholder: 'Write a Comment', :class => "input" %><br/></p>
          <%= f.button :submit, :class => "primaryContained" %>
        <% end %>
      </div><!-- End col -->
    </div><!--End Row -->
  </div><!--End Container -->
</section><!-- end App -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="nav navbar-header">
          <%= link_to "Social App", root_path, :class => 'navbar-brand' %>
        </div>
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <div class="move-right">
              <li><%= "Hello #{current_user.email} !" %></li>
              <li><%=link_to "Log out", destroy_user_session_path, method: "delete" %></li>
              <li><%= link_to "New Post", new_post_path %></li>
            </div>
          <% else %>
          <div class="move-right">
            <li><%=link_to "Sign Up",  new_user_registration_path %></li>
            <li><%=link_to "Login", new_user_session_path %></li>
          </div>
          <% end %>
        </ul>
      </div>
    </nav>

    <div style="display: flex; justify-content: center;">
      <% if notice %>
        <p class="text-center alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
         <p class="text-center alert alert-danger"><%= alert %></p>
      <% end %>
    </div>

    <br/>
    <div class ="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_post_form.html.erb
 <div class="col-md-6 col-md-offset-3">
  <div class="new-post-form">
    <h1>New Post</h1>
      <%= simple_form_for @post, :html => {multipart: true} do |f| %>
        <%= f.input :title, :required=> true %>
        <%= f.input :body, as: "text", input_html: {:cols => '10', :rows => '8'}, :required=> true %><br>
        <%= f.file_field :image, accept: 'image/png, image/jpeg', direct_upload: true %><br/><br/>
        <%= f.button :submit , class: 'btn-custom2' %>
      <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h4>Edit Post Form</h4>
<%= render "post_form" %>

app/views/posts/index.html.erb
<div align="center">
  <h1>All Posts</h1>
  <% if @posts.count.zero? %>
    <center><h1>No Posts Here!</h1></center>
  <% end %>
  <% @posts.each do |post| %>
    <div class="posts mb-4">
      <div class="post-content">
        <a href="/posts/<%= post.id %>">
          <b><h3 class="post-title"><%= post.title %></h3></b>
        </a>
        <% if post.image.attached? %>
          <p class="post-image index-image"><img src="<%= (url_for(post.image)) if post.image.attached? %>"> </p>
        <% end %>
        <p class="post-title"><%= post.body %></p>
      </div>
    </div>

  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "post_form" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="post-info">
      <h2 class="post-title"><%= @post.title %> </h2>
      <p class="post-description"> <%= @post.body %> </p>

      <% if user_signed_in? %>
        <% if @post.user == current_user %>
        <div class="btn-group">
          <%= link_to "Edit Post", edit_post_path(@post), class: "btn primaryContained" %>
          <%= link_to "Delete Post", post_path(@post), method: :delete , data: {confirm: "Are you sure?"}, class: "btn primaryContained" %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if @post.image.attached? %>
    <div class="col-md-4">
      <img src="<%= (url_for(@post.image)) %>", class= "post-show">
    </div>
  <% end %>
</div>

<div class="row">
  <div class="comments">
    <div id="commentParent">
      <% if @post.comments.any? %>
      <h2>Comments</h2>
      <%= render "/comments/index" %>
      <% else %>
      <h5>No Comments!</h5>
      <% end %>
    </div>

    <% if user_signed_in? %>
      <h2>Add comment</h2>
      <%= render "comments/new", post: @post%>
    <% else %>
      <p>You Are Required To Sign Up!</p>
    <% end %>
  </div>
</div>